# -*- coding: utf-8 -*-
"""

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QmqqF3cAOjVibqd5Q82k4QoVDFBh2cOl
"""

with open('gameclauses_1.krf') as f1:
    lines_1 = f1.readlines()

with open('gameclauses_2.krf') as f2:
    lines_2 = f2.readlines()


new_list = list()
start_prev = 0
start_next = 0
for i in range(1, len(lines_1)):
  if(lines_1[i] == '\n'):
    start_prev = start_next
    end_prev = i-1
    start_next = i+1
    if(end_prev - start_prev > 9):
      new_list.append(lines_1[start_prev:end_prev])

start_prev = 0
start_next = 0
for i in range(0, len(lines_2)):
  if(lines_2[i] == '\n'):
    start_prev = start_next
    end_prev = i-1
    start_next = i+1
    if(end_prev - start_prev > 9):
      new_list.append(lines_2[start_prev:end_prev])

len(new_list)

with open('game_ontology7.txt', 'w') as f: # change the number at game_ontology<number>
    for item in new_list[2400:len(new_list)]: # change the numbers in the list from 0:400 in the multiples of 400 till the len(new_list)
      for element in item:
        f.write("%s" % element)
      f.write("\n")