# -*- coding: utf-8 -*-
"""

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19r300_7fN5TdK1TJQGXGo7NFznX_ZefC
"""

with open('gameclausesxx.txt') as f:
    lines = f.readlines()


new_lines = list()
for line in lines:
  temp = line.replace("\', \'(isa ", "\',, \'(isa ")
  temp = temp.split(",, ")
  for temp1 in temp:
    new_lines.append(temp1)


final_lines = list()
count = 0
for line in new_lines:
  temp = line.replace("\', \'", "\',, \'")
  temp = temp.split(",, ")
  for i in range(len(temp)):
    temp[i] = temp[i].replace("[","").replace("\'", "").replace("]", "").replace("\n", "")
  final_lines.append(temp)
  count += 1
  if((count + 1) % 5000 == 0): print(str(count+1) + " are done")

removes = list()
for i in range(len(final_lines)):
  isa_line_i = [s for s in final_lines[i] if 'isa' in s]
  for j in range(i, len(final_lines)):
    isa_line_j = [s for s in final_lines[j] if 'isa' in s]
    if(i != j):
      if(isa_line_i == isa_line_j):
        removes.append(j)

removes = list(set(removes))

temp_lines = final_lines
final_lines = list()
for i in range(len(temp_lines)):
  if i not in removes:
    final_lines.append(temp_lines[i])

with open("temp78.txt", "w") as text_file:
  text_file.write("%s" % "\n")
  for lines in final_lines:
    for line in lines:
      text_file.write("%s" % line)
      text_file.write("%s" % "\n")
    text_file.write("%s" % "\n")

# with open("temp.txt", "w") as text_file:
#   text_file.write("(in-microtheory GameRecommenderMT)")
#   text_file.write("%s" % "\n")
#   for lines in final_lines:
#     for line in lines:
#       text_file.write("%s" % line)
#       text_file.write("%s" % "\n")
#     text_file.write("%s" % "\n")